Volume circuits
unitaryfund/mitiq pull request #1281
Opened 2022-05-13 03:41 UTC by nickdgardner

Description
-----------

Adapted Cirq code from [here](https://github.com/quantumlib/Cirq/blob/v0.14.1/cirq-core/cirq/contrib/quantum_volume/quantum_volume.py) to implement a function 
generate_volume_circuit which returns:
-a random circuit of the form used in quantum volume experiments, and
-the heavy set of bit strings associated with the returned circuit

NOTE: not tested

Checklist
---------

Check off the following once complete (or if not applicable) after opening the PR. The PR will be reviewed once this checklist is complete and all tests are passing.

- [ ] I added unit tests for new code.
- [x] I used [type hints](https://www.python.org/dev/peps/pep-0484/) in function signatures.
- [x] I used [Google-style](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) docstrings for functions.
- [ ] I [updated the documentation](../blob/master/docs/CONTRIBUTING_DOCS.md) where relevant.
- [ ] Added myself / the copyright holder to the AUTHORS file

If some items remain, you can mark this a [draft pull request](https://github.blog/2019-02-14-introducing-draft-pull-requests/).

License
-------

- [ ] I license this contribution under the terms of the GNU GPL, version 3 and grant Unitary Fund the right to provide additional permissions as described in section 7 of the GNU GPL, version 3.

Tips
----

- If the validation check fails:

    1. Run `make check-types` (from the root directory of the repository) and fix any [mypy](https://mypy.readthedocs.io/en/stable/) errors.

    2. Run `make check-style` and fix any [flake8](http://flake8.pycqa.org) errors.

    3. Run `make format` to format your code with the [black](https://black.readthedocs.io/en/stable/index.html) autoformatter.

  For more information, check the [Mitiq style guidelines](https://mitiq.readthedocs.io/en/stable/contributing.html#style-guidelines).

- Write "Fixes #XYZ" in the description if this PR fixes Issue #XYZ.

2022-05-13 12:12 UTC, nathanshammah commented
Good to see this started @nickdgardner. Nice modular approach and good start formatting the docstrings with google-style formalism. Great to see the test file already in place. Remember to add the new module to the API docs, in the index file.

2022-05-13 13:45 UTC, andreamari commented
Hi @nickdgardner, 
if possible it is much better to directly import functions from Cirq instead of manually copying their code.

For example what you did is could be (more or less) simplified as follows:
 
```

from cirq.contrib.quantum_volume import compile_circuit, generate_model_circuit, compute_heavy_set

def generate_volume_circuit(....):
    circuit_model = generate_model_circuit(num_qubits, depth=num_qubits) 
    heavy_set = compute_heavy_set(circuit_model)
    
    return circuit_model, heavy_set 
```

Other suggestions: 

- Given that `generate_model_circuit` has a depth parameter, I would keep it instead of forcing a square circuit.
- The has generic numerica 4X4 unitaries instaed of elementary gates. This may be ok for the moment but eventually we need to change this aspect. We want circuits composed of elementary gates. Maybe we could use something like 
`circuit = cirq.decompose(circuit_model)`.    
Also `cirq.contrib.quantum_volume.compile_circuit` seems related to this problem but I am not sure how it works.

2022-05-20 14:35 UTC, andreamari commented
I have some preliminary suggestions that you could consider:

- Adding `from mitiq.benchmarks.volume_circuits import generate_volume_circuit` in the benchmarks `__init__` file. Such that your function can be imported from `mitiq.benchmarks`.
- Adding `from cirq import decompose as cirq_decompose` to be used in next point.
- Adding a `decompose` optional argument in your function with default value `False`. If true the previous `cirq_decompose` is used before converting the circuit. I mean something like
```
    circuit = generate_model_circuit(num_qubits, depth)
    heavy_set = compute_heavy_set(circuit)
    if decompose:
        circuit = Circuit(cirq_decompose(circuit))

    return_type = "cirq" if not return_type else return_type
    circuit = convert_from_mitiq(circuit, return_type) 
```
- Adding an optional `seed` argument. See e.g. [the mirror circuit function](https://github.com/unitaryfund/mitiq/blob/41af9cf602a95fb99b040d43063e3001d66f543e/mitiq/benchmarks/mirror_circuits.py#L138).

2022-05-20 18:24 UTC, nickdgardner commented
@andreamari Great, thanks for the feedback. I'll make these changes soon. One question re decomposing the circuit for a particular device: is it worth trying to incorporate the compile_circuit function [here](https://github.com/quantumlib/Cirq/blob/master/cirq-core/cirq/contrib/quantum_volume/quantum_volume.py
) that you mentioned above?

It supports compiling "the given model circuit onto the given device graph". Would that be useful for how the quantum volume circuits will be used for benchmarking in mitiq?

2022-05-20 21:20 UTC, nickdgardner commented
@andreamari Also another question about decomposing the numerical matrix-defined unitaries into gates. comments (below) in cirq's function `generate_model_circuit` seem to imply that it returns a circuit already decomposed into supported gates, but as far as I can tell it doesn't--the function can return only circuits consisting of matrix-defined unitaries. Am I missing something or is the comment just misleading?

`
# For each layer.
    for _ in range(depth):
        # Generate uniformly random permutation Pj of [0...n-1]
        perm = random_state.permutation(num_qubits)

        # For each consecutive pair in Pj, generate Haar random SU(4)
        # Decompose each SU(4) into CNOT + SU(2) and add to Ci
        for k in range(0, num_qubits - 1, 2):
            permuted_indices = [int(perm[k]), int(perm[k + 1])]
            special_unitary = cirq.testing.random_special_unitary(4, random_state=random_state)

            # Convert the decomposed unitary to Cirq operations and add them to
            # the circuit.
            circuit.append(
                cirq.MatrixGate(special_unitary).on(
                    qubits[permuted_indices[0]], qubits[permuted_indices[1]]
                )
            )

`

2022-05-23 14:11 UTC, andreamari commented
> @andreamari Also another question about decomposing the numerical matrix-defined unitaries into gates. comments (below) in cirq's function `generate_model_circuit` seem to imply that it returns a circuit already decomposed into supported gates, but as far as I can tell it doesn't--the function can return only circuits consisting of matrix-defined unitaries. Am I missing something or is the comment just misleading?
> 
> ```
>     # For each layer.
>     for _ in range(depth):
>         # Generate uniformly random permutation Pj of [0...n-1]
>         perm = random_state.permutation(num_qubits)
> 
>         # For each consecutive pair in Pj, generate Haar random SU(4)
>         # Decompose each SU(4) into CNOT + SU(2) and add to Ci
>         for k in range(0, num_qubits - 1, 2):
>             permuted_indices = [int(perm[k]), int(perm[k + 1])]
>             special_unitary = cirq.testing.random_special_unitary(4, random_state=random_state)
> 
>             # Convert the decomposed unitary to Cirq operations and add them to
>             # the circuit.
>             circuit.append(
>                 cirq.MatrixGate(special_unitary).on(
>                     qubits[permuted_indices[0]], qubits[permuted_indices[1]]
>                 )
>             )
> ```

Thanks @nickdgardner !
This is what I understood after playing a bit with those functions on a jupyter notebook, but I may be wrong.

- The function `generate_model_circuit` generates circuits with two-qubit unitaries unitaries between arbitrary pairs of qubits.
-  The function cirq.contrib.quantum_volume.compile_circuit also seems to return numerical unitaries (if I remember correctly) but probably the two-qubit unitaries involve only qubits that are directly connected on the device graph. 
- The function `cirq.decompose` sems to work in converting numerical unitaries to gates,  but probably the decomposition is not optimal for generic non-Cirq hardware. This is why i suggest to apply it only as a non-default option. After all, for non-Cirq frontends, conversion functions already seem to convert matrix unitaries to gates. You can test this by using a non-Cirq circuit with your existing function.

Finally, regarding your question about adding the option of _compiling the circuit for a given device graph_.  If we add this, I would keep it optional (e.g. by assuming a fully connected graph as default option). Moreover, if we add this, we must ensure that the device graph can be passed to the function as a frontend independent object.  
In practice,if the device graph can be specified as a `networkx` graph with simple integer nodes, this is fine. If instead the device graph must some Cirq-specific object, this is bad since Mitiq functions should be a frontend independent as possible.

2022-05-27 14:33 UTC, andreamari reviewed
Thanks @nickdgardner! Very good PR, congratulations! 
I just left a few small suggestions.

A tip for (hopefully more) future PRs: if you click on the _Files changed_ tab you get warnings if some lines of codes are not tested.

2022-05-27 14:33 UTC, andreamari commented on mitiq/benchmarks/tests/test_volume_circuits.py
> +    assert computed_heavy_set == true_heavy_set
Nice test!

2022-05-27 14:33 UTC, andreamari commented on mitiq/benchmarks/volume_circuits.py
> +            unitary matrix gates into simpler gates defined in cirq.ops
```suggestion
            unitary matrix gates into simpler gates.
```
Better to keep it simpler. Gates can be converted differently depending on frontends.

2022-05-27 14:33 UTC, andreamari commented on mitiq/benchmarks/volume_circuits.py
> +from cirq.value import big_endian_int_to_bits
Nice catch!

2022-05-27 14:33 UTC, andreamari commented on mitiq/benchmarks/volume_circuits.py
> +        )
I guess we can remove this check since the cirq function will give a similar error. If instead we want to keep it, we should test it.

2022-05-27 14:33 UTC, andreamari commented on mitiq/benchmarks/volume_circuits.py
> +        circuit = Circuit(cirq_decompose(circuit))
We need a specific test for this option. Currently it's never tested.

2022-05-27 16:52 UTC, nathanshammah reviewed
Looks great! I made a small general comment that though I think is important for users, to change the name of functions modules from `volume_circuits` etc. to `quantum_volume_circuits`, as it has a very specific meaning anyone can immediately relate to.

2022-05-27 16:52 UTC, nathanshammah commented on docs/source/apidoc.rst
> +Volume Circuits
I suggest using the more standard "Quantum Volume Circuits" instead of just "Volume Circuits" , as it has a quite specific meaning.

2022-05-27 16:52 UTC, nathanshammah commented on mitiq/benchmarks/__init__.py
> +from mitiq.benchmarks.volume_circuits import generate_volume_circuit
also here, even if it's long, I suggest having `generate_quantum_volume_circuit`

2022-05-27 16:52 UTC, nathanshammah commented on mitiq/benchmarks/volume_circuits.py
> +# Copyright (C) 2022 Unitary Fund
I suggest calling this file either `quantum_volume` or `quantum_volume_circuits` for homogeneity with the other modules.

2022-05-27 16:52 UTC, nathanshammah commented on mitiq/benchmarks/tests/test_volume_circuits.py
> +"""Tests for volume circuits. The cirq functions that do the main work
```suggestion
"""Tests for quantum volume circuits. The Cirq functions that do the main work
```

2022-05-27 16:52 UTC, nathanshammah commented on mitiq/benchmarks/volume_circuits.py
> +volume experiments as defined in https://arxiv.org/abs/1811.12926.
Can you please add this paper to the references, if it is not included yet? 
The references file is [here](https://github.com/unitaryfund/mitiq/blob/master/docs/source/refs.bib).

2022-05-27 16:52 UTC, nathanshammah commented on mitiq/benchmarks/volume_circuits.py
> +cirq-core/cirq/contrib/quantum_volume/quantum_volume.py
Actually reusing part of this + some basic functioning would make a great Example for the example section in the Documentation, for another follow-up PR.

2022-05-30 01:02 UTC, nickdgardner commented
@andreamari @nathanshammah Ok I think all the issues are resolved! Let me know if I missed anything, and thanks for the feedback.

2022-05-31 08:48 UTC, andreamari approved these changes
LGTM! Thanks @nickdgardner

2022-05-31 08:48 UTC, andreamari commented on docs/source/refs.bib
> +  doi={https://doi.org/10.1103/PhysRevA.100.032328}
```suggestion
  publisher={APS},
  url={https://journals.aps.org/pra/abstract/10.1103/PhysRevA.100.032328},
  doi={https://doi.org/10.1103/PhysRevA.100.032328},
```

2022-05-31 08:49 UTC, andreamari commented on docs/source/refs.bib
> +  doi={https://doi.org/10.1103/PhysRevA.100.032328}
This commit is to try fixing the bibtex error

2022-05-31 10:18 UTC, nathanshammah requested changes

2022-05-31 10:18 UTC, nathanshammah commented on docs/source/apidoc.rst
> +^^^^^^^^^^^^
```suggestion
Quantum Volume Circuits
^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

2022-05-31 11:23 UTC, nathanshammah approved these changes
Thank you @nickdgardner! Looks great!

2022-05-31 11:23 UTC, merged