[Classical Shadows] Rotation gate functions
unitaryfund/mitiq pull request #1903
Opened 2023-07-09 22:10 UTC by Min-Li

## Description
Rotation gates and test for #1899 ( fixed #1878)

---

### License

- [x] I license this contribution under the terms of the GNU GPL, version 3 and grant Unitary Fund the right to provide additional permissions as described in section 7 of the GNU GPL, version 3.

Before opening the PR, please ensure you have completed the following where appropriate.
- [x] I added unit tests for new code.
- [x] I used [type hints](https://www.python.org/dev/peps/pep-0484/) in function signatures.
- [x] I used [Google-style](https://google.github.io/styleguide/pyguide.html#383-functions-and-methods) docstrings for functions.
- [ ] I [updated the documentation](../blob/master/docs/CONTRIBUTING_DOCS.md) where relevant.
- [ ] Added myself / the copyright holder to the AUTHORS file

2023-07-09 23:59 UTC, purva-thakre commented
@Min-Li In case you haven't noticed, you can check the style guidelines locally so that `validate` can pass.

https://mitiq.readthedocs.io/en/stable/contributing.html#style-guidelines

2023-07-10 15:45 UTC, nathanshammah requested changes
Thanks @Min-Li, this looks very nice. Thanks for adding the tests. Please add the new module to the API doc file ([apidoc.md](https://github.com/unitaryfund/mitiq/blob/master/docs/source/apidoc.md)) in the documentation. Once we have those, you can test locally with make docs that they generate correctly on the API-doc page. On remote, you can check the documentation for this PR [here](https://mitiq--1899.org.readthedocs.build/en/1903/).

2023-07-10 15:45 UTC, nathanshammah commented on mitiq/shadows/rotation_gates.py
> +    # return "XXXYZYZX" where len string == num_qubits
Please add a docstring using the Google-style format used also in other functions (such as `get_rotated_circuits`).

2023-07-10 20:38 UTC, nathanshammah commented
@Min-Li here you can check the new docs, with the `get_rotated_circuits` function showing up correctly: https://mitiq--1903.org.readthedocs.build/en/1903/apidoc.html#module-mitiq.shadows.rotation_gates. I added some more reviewers, not all need to review, but trying to speed up the process.

2023-07-11 13:54 UTC, andreamari reviewed
Thanks @Min-Li, just minor suggestions. Nice work.

2023-07-11 13:54 UTC, andreamari commented on mitiq/shadows/rotation_gates.py
> +          of length `num_qubits`.
```suggestion
        A list of random Pauli strings.
```
Since function arguments are already explained before.

2023-07-11 13:54 UTC, andreamari commented on mitiq/shadows/rotation_gates.py
> +# generate N random Pauli strings for given number of qubits
```suggestion
# Functions to implement random Pauli measurements.
```

2023-07-11 13:54 UTC, andreamari commented on mitiq/shadows/rotation_gates.py
> +    # Sample random Pauli operators uniformly from X, Y, Z
```suggestion
```
I think we can cut this comment.

2023-07-11 13:54 UTC, andreamari commented on mitiq/shadows/rotation_gates.py
> +# attach random rotate gates to N copies of the circuit
```suggestion
```
This is now explained in the function docstring.

2023-07-11 13:54 UTC, andreamari commented on mitiq/shadows/rotation_gates.py
> +        followed by a measurement.
```suggestion
    """Returns a list of circuits that are identical to the input circuit,
    except that each one has single-qubit Clifford gates followed by
    measurement gates that are designed to measure the input
    Pauli strings in the Z basis.
```

2023-07-11 13:54 UTC, andreamari commented on mitiq/shadows/rotation_gates.py
> +            before measuring.
```suggestion
        pauli_strings: The Pauli strings to measure in each output circuit.
```

2023-07-11 13:54 UTC, andreamari commented on mitiq/shadows/rotation_gates.py
> +            string.
```suggestion
        The list of circuits with rotation and measurement gates appended.
```

2023-07-11 13:54 UTC, andreamari commented on mitiq/shadows/test/test_rotation_gates.py
> +    # print(rotated_circuits)
```suggestion
```

2023-07-11 13:54 UTC, andreamari commented on mitiq/shadows/test/test_rotation_gates.py
> +def test_get_rotated_circuits():
This test function is good but it doesn't test that circuits are rotated correctly. 

Can we add an additional test function to check this aspect in some way? 
E.g., we can pick a specific circuit and a specific bitstring and assert that the `rotated_circuit==expeted_circuit`, where `expected_circuit` is manually defined. 
Or any other way you prefer, as long as we test the intended action of the function.

2023-07-12 00:12 UTC, Min-Li commented
Will integrate these functions in z-basis measurement (#1906 ) and renamed as `quantum_processing`

2023-07-12 00:12 UTC, closed without merging