added tensorflow quantum executor example to documentation
unitaryfund/mitiq pull request #348
Opened 2020-09-09 13:48 UTC by k-m-schultz

Description
-----------
Fixes #334 

Checklist
-----------
Please make sure you have finished the following tasks before requesting a review of the pull request (PR). For more information, please refer to the [Contributor's Guide](../blob/master/CONTRIBUTING.md):

- [ ] Contributions to mitiq should follow the [pep8 style](https://www.python.org/dev/peps/pep-0008/). You can enforce it easily with [`black`][black] style and with [`flake8`][flake8] conventions.
- [ ] Please add tests to cover your changes, if applicable, and make sure that all new and existing tests pass locally.
- [ ] If the behavior of the code has changed or new feature has been added, please also [update the documentation](../blob/master/docs/CONTRIBUTING_DOCS.md).
- [ ] Functions and classes have useful [Google-style][google] docstrings and [type hints][hints] in the signature of the objects.
- [ ] (Bug fix) The associated issue is referenced above using [auto-close keywords][auto-close]. If the PR fixes an issue, use the keyword fix/fixes/fixed followed by the issue id. For example, if the PR fixes issue 1184, type "Fixes #1184" (without quotes).
- [ ] The [changelog][changelog] is updated, including author and PR number (@username, gh-xxx).

[auto-close]: https://help.github.com/en/articles/closing-issues-using-keywords
[black]: https://black.readthedocs.io/en/stable/index.html
[changelog]: https://github.com/unitaryfund/mitiq/blob/master/CHANGELOG.md
[contributing]: https://github.com/unitaryfund/mitiq/blob/master/CONTRIBUTING.md
[docs]: https://github.com/unitaryfund/mitiq/blob/master/docs/source/
[flake8]: http://flake8.pycqa.org
[google]: https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html
[hints]: https://www.python.org/dev/peps/pep-0484/
[pep-484]: https://www.python.org/dev/peps/pep-0484/

2020-09-29 17:09 UTC, nathanshammah commented
I looked a bit into this as I was curious if just tweaking `doctest_global_setup` in the `conf.py` file would suffice, but indeed it seems that the libraries would need to be installed by the requirements anyways. 

Another problem is that [TF-quantum](https://github.com/tensorflow/quantum/issues/290) (and TF) does not support python 3.8, which is supported by Mitiq. My advice would be to forget the testing of this executor example and just use the `code-block` directive, at least for the time being. 

This is an example in which a separate `mitiq-examples` folder may be of help maybe, as it would allow a notebook to be installed with its dependencies. How the unit testing of notebooks works is not clear though.

2020-09-29 17:38 UTC, nathanshammah commented
Just a note: the python 3.8 compatibility issue may be bypassed by installing [`tfq-nightly`](https://pypi.org/project/tfq-nightly/), which supports python 3.8. 

However, I cannot check it now, as something is messing with the sphinx doctests on my machine, which throw some 27 issues on circuits not being drawn as expected, as it downgraded cirq to v.0.8. Even by pip-uninstalling cirq, pip installing the 0.9dev version we pinned does not work properly for me, it may have messed something in my conda environment.

2020-10-02 03:34 UTC, karalekas requested changes
In addition to the inline comments (most of which are spacing related, but some of which are important like the assertion issue) this is what I suggest in order to make it so this PR will build and test the tfq code in the docs.

1. Add a new file `docs/requirements.txt` with two lines: `tensorflow~=2.3.1` and `tfq-nightly~=0.4.0.dev20201001`.

2. Install the requirements in this file when building the docs in `.github/workflows/ci.yml`. Specifically, there is a job named `docs` with a `run` entry in it. The run entry should have a new line added to it: `pip install -r docs/requirements.txt`. For extra clarity:

```yaml
- name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          make install requirements
```

should change to

```yaml
- name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          make install requirements
          pip install -r docs/requirements.txt
```

After making those two changes, and addressing the review comments, the build should work (it works for me locally).

Finally, make sure to add an entry to the changelog! Thanks for contributing! :)

**Note to self**: Make issue to add docs requirements installation instructions after this is merged.

2020-10-02 03:34 UTC, karalekas commented on docs/source/guide/guide-executors.rst
> +    def stochastic_bit_flip_simulation(circ: Circuit, p, num_MC=100):
might as well add typing to the rest of this signature

2020-10-02 03:34 UTC, karalekas commented on docs/source/guide/guide-executors.rst
> +        #Create array of symbolic variables and reshape to natural circuit parameterization
```suggestion
        # Create array of symbolic variables and reshape to natural circuit parameterization
```

2020-10-02 03:34 UTC, karalekas commented on docs/source/guide/guide-executors.rst
> +        #Symbolicly add X gates to the input circuit
```suggestion
        # Symbolicly add X gates to the input circuit
```

2020-10-02 03:34 UTC, karalekas commented on docs/source/guide/guide-executors.rst
> +        for i,moment in enumerate(circ.moments):
```suggestion
        for i, moment in enumerate(circ.moments):
```

2020-10-02 03:34 UTC, karalekas commented on docs/source/guide/guide-executors.rst
> +            for j,q in enumerate(circ.all_qubits()):
```suggestion
            for j, q in enumerate(circ.all_qubits()):
```

2020-10-02 03:34 UTC, karalekas commented on docs/source/guide/guide-executors.rst
> +                noisy_circuit.append(cirq.rx(h_array[j,i]).on(q))
```suggestion
                noisy_circuit.append(cirq.rx(h_array[j, i]).on(q))
```

2020-10-02 03:34 UTC, karalekas commented on docs/source/guide/guide-executors.rst
> +        #rotations will be pi w/ prob p, 0 w/ prob 1-p
```suggestion
        # rotations will be pi w/ prob p, 0 w/ prob 1-p
```

2020-10-02 03:34 UTC, karalekas commented on docs/source/guide/guide-executors.rst
> +        vals = [np.reshape((np.random.rand(len(circ.all_qubits()),len(circ.moments))<p)*np.pi,(1,len(circ.all_qubits())*len(circ.moments))) for _ in range(num_MC)]
maybe break this up so it's readable?

2020-10-02 03:34 UTC, karalekas commented on docs/source/guide/guide-executors.rst
> +        h_array = np.asarray(h).reshape((len(circ.all_qubits()),len(circ.moments)))
ditto here re: readability -- some breaking up & spaces would likely help

2020-10-02 03:34 UTC, karalekas commented on docs/source/guide/guide-executors.rst
> +        #Instantiate tfq layer for computing state vector
```suggestion
        # Instantiate tfq layer for computing state vector
```

2020-10-02 03:34 UTC, karalekas commented on docs/source/guide/guide-executors.rst
> +        #Execute monte carlo sim with symbolic values specified by vals
```suggestion
        # Execute monte carlo sim with symbolic values specified by vals
```

2020-10-02 03:34 UTC, karalekas commented on docs/source/guide/guide-executors.rst
> +        out = state(noisy_circuit,symbol_names=h,symbol_values=vals).to_tensor()
```suggestion
        out = state(noisy_circuit, symbol_names=h, symbol_values=vals).to_tensor()
```

2020-10-02 03:34 UTC, karalekas commented on docs/source/guide/guide-executors.rst
> +        #Fancy way of computing and summing individual density operators, follwed by averaging
```suggestion
        # Fancy way of computing and summing individual density operators, followed by averaging
```

2020-10-02 03:34 UTC, karalekas commented on docs/source/guide/guide-executors.rst
> +        dm = tf.tensordot(tf.transpose(out),tf.math.conj(out),axes=[[1],[0]]).numpy()/num_MC
```suggestion
        dm = tf.tensordot(tf.transpose(out), tf.math.conj(out), axes=[[1], [0]]).numpy() / num_MC
```

2020-10-02 03:34 UTC, karalekas commented on docs/source/guide/guide-executors.rst
> +        #return measurement of 0 state
```suggestion
        # return measurement of 0 state
```

2020-10-02 03:34 UTC, karalekas commented on docs/source/guide/guide-executors.rst
> +        return np.real(dm[0,0])
```suggestion
        return np.real(dm[0, 0])
```

2020-10-02 03:34 UTC, karalekas commented on docs/source/guide/guide-executors.rst
> +.. code::
change back to testcode

2020-10-02 03:34 UTC, karalekas commented on docs/source/guide/guide-executors.rst
> +.. testcode::
can uncomment this after you make the changes in my top-level review regarding requirements

2020-10-02 03:34 UTC, karalekas commented on docs/source/guide/guide-executors.rst
> +    #assert .97 < out < 1
this fails sometimes. i've seen values as low as 0.93999755. so this range will have to be extended

2020-10-15 15:39 UTC, nathanshammah requested changes
Thank you @k-m-schultz. 
I added some comments requesting some changes:
- on the `docs/requirements.txt` file: adding information in the documentation, [here](https://github.com/unitaryfund/mitiq/blob/master/docs/CONTRIBUTING_DOCS.md#requirements), and merging the requirements for docs present in the main `requirements.txt` file. 
- Note that TF Quantum has a [0.4.0 release](https://github.com/tensorflow/quantum/releases/tag/0.4.0), that maybe works with what is needed? Better to ping a released version than a development one. I don't know if that will make conflicts arise with dependencies, as it requires numpy 1.5 and mitiq pins 1.5.
- a small suggestion: renaming `num_MC` to `num_montecarlo` or `montecarlo_repetitions` 
would be more explicit and slightly more "pythonic"
- It is nice the use of `sympy` symbols, this could be highlighted in the text, possibly.
- Most requests by @karalekas are implemented, but there are some outstanding comments to the code that need to be resolved or debated. Thanks!

2020-10-16 14:41 UTC, k-m-schultz commented on docs/requirements.txt
> +tfq-nightly~=0.4.0.dev20201001
Locally, I verified this works with the tensorflow-quantum 0.4.0, so I will make that change to docs/requirements.  Not sure what to do about the other requirements from requirements.txt, let me know.

2020-10-23 10:22 UTC, nathanshammah reviewed
LGTM, thanks @k-m-schultz! I made a small refactoring of the first two lines of the simulation to address Peter's comment.

2020-10-23 10:22 UTC, nathanshammah commented on docs/source/guide/guide-executors.rst
> +        h_array = np.asarray(h).reshape((len(circ.all_qubits()),len(circ.moments)))
```suggestion
        total_range = len(circ.moments) * len(circ.all_qubits())
        for i in range(total_range):
           to_join = 'h_{0} '.format(i) 
        h = sympy.symbols(''.join([to_join]), positive = True)
        h_array = np.asarray(h).reshape((len(circ.all_qubits()), len(circ.moments)))
```

2020-10-26 23:46 UTC, karalekas approved these changes

2020-10-26 23:48 UTC, merged

2020-10-26 23:49 UTC, karalekas commented
Thanks for your contribution @k-m-schultz! :)

2020-10-27 14:54 UTC, nathanshammah commented
Thanks @karalekas.

2021-07-02 00:45 UTC, crazy4pi314 commented
@all-contributors please add @k-m-schultz for example