Makes mitiq.about() clearer on which packages are required/optional, removes install path.
unitaryfund/mitiq pull request #399
Opened 2020-10-07 17:11 UTC by rmlarose

Fixes #377.

2020-10-08 23:12 UTC, karalekas reviewed
I'm feeling like I might prefer "Core Dependencies" and "Optional Dependencies" (with dependencies capitalized) but I could be persuaded. I honestly like the word requirements more than dependencies but I guess "optional requirements" is a bit awk. Otherwise LGTM.

2020-10-09 02:05 UTC, karalekas requested changes
One last tiny thing -- the changelog entry is in the wrong spot. Should be below "All Changes". You will have to rebase off of master before making this change, otherwise there will be a conflict.

2020-10-09 02:10 UTC, rmlarose commented
Oops, good catch @karalekas.

2020-10-09 02:13 UTC, karalekas approved these changes

2020-10-09 02:26 UTC, merged