Fixes #397
unitaryfund/mitiq pull request #400
Opened 2020-10-07 21:58 UTC by erkska

Fixes #397

Description
-----------
Fixed the bug where links didn't work.

2020-10-07 23:12 UTC, rmlarose commented on CONTRIBUTING.md
> +Follow the guidelines in the Contributing to docs [instructions](https://mitiq.readthedocs.io/en/latest/README.html) (look here on [GitHub](https://github.com/unitaryfund/mitiq/blob/master/README.md)
```suggestion
Follow these [instructions for contributing to the documentation](https://mitiq.readthedocs.io/en/latest/contributing_docs.html) which include guidelines about updating the API-doc list of modules and writing examples in the users guide.
```

2020-10-07 23:14 UTC, rmlarose requested changes
Thanks @erkska. One wrong link and I suggested a change to our previous wording.

2020-10-08 04:47 UTC, erkska commented
Commited that change, whats the deal with wrong link?

2020-10-08 06:42 UTC, rmlarose approved these changes
Thanks! The link went to the readme when it should have gone to the contribution guidelines.

2020-10-08 06:43 UTC, merged

2021-07-02 00:49 UTC, crazy4pi314 commented
@all-contributors please add @LogMoss for doc, bug