Qiskit exec
unitaryfund/mitiq pull request #463
Opened 2020-12-04 08:14 UTC by pchung39

Description
-----------
This pull request is for #379 . I've transferred the Qiskit executors referenced in the back-end executors documentation  ([Back-End Executors](https://mitiq.readthedocs.io/en/stable/guide/guide-executors.html)) into `/mitiq_qiskit/qiskit_utils.py`. There were two existing function in `qiskit_utils.py` named `random_one_qubit_identity_circuit` and `run_with_noise` that I left untouched in the file. 

I also included a few tests for the added executors. They are pretty straight-forward but should cover basic functionality! Let me know if there are any additional use cases that you feel should be included.

Thanks so much! 

Checklist
-----------
Please make sure you have finished the following tasks before requesting a review of the pull request (PR). For more information, please refer to the [Contributor's Guide](../blob/master/CONTRIBUTING.md):

- [x] Contributions to mitiq should follow the [pep8 style](https://www.python.org/dev/peps/pep-0008/). You can enforce it easily with [`black`](https://black.readthedocs.io/en/stable/index.html) style and with [`flake8`](http://flake8.pycqa.org) conventions.
- [x] Please add tests to cover your changes, if applicable, and make sure that all new and existing tests pass locally.
- [x] If the behavior of the code has changed or new feature has been added, please also [update the documentation](../blob/master/docs/CONTRIBUTING_DOCS.md).
- [x] Functions and classes have useful [Google-style](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) docstrings and [type hints](https://www.python.org/dev/peps/pep-0484/) in the signature of the objects.
- [x] (Bug fix) The associated issue is referenced above using [auto-close keywords](https://help.github.com/en/articles/closing-issues-using-keywords). If the PR fixes an issue, use the keyword fix/fixes/fixed followed by the issue id. For example, if the PR fixes issue 1184, type "Fixes #1184" (without quotes).
- [ ] The [changelog](https://github.com/unitaryfund/mitiq/blob/master/CHANGELOG.md) is updated, including author and PR number (@username, gh-xxx).

2020-12-11 07:54 UTC, pchung39 commented
@rmlarose alright! This pull request is ready for a review 😄

2021-01-06 13:08 UTC, rmlarose commented on mitiq/mitiq_qiskit/qiskit_utils.py
> +def qs_wvf_sampling_sim(
```suggestion
def execute(
```

2021-01-06 13:08 UTC, rmlarose commented on mitiq/mitiq_qiskit/qiskit_utils.py
> +            f"no classical bits.")
```suggestion
            "no classical bits.")
```

2021-01-06 13:09 UTC, rmlarose commented on mitiq/mitiq_qiskit/qiskit_utils.py
> +def qs_wvf_sim(
```suggestion
def execute(
```

2021-01-06 13:10 UTC, rmlarose commented on mitiq/mitiq_qiskit/qiskit_utils.py
> +def qs_noisy_sampling_sim(
```suggestion
def execute_with_depolarizing_noise(
```

2021-01-06 13:11 UTC, rmlarose commented on mitiq/mitiq_qiskit/qiskit_utils.py
> +    counts = results.get_counts()
```suggestion
    counts = job.result().get_counts()
```

2021-01-06 13:12 UTC, rmlarose commented on mitiq/mitiq_qiskit/qiskit_utils.py
> +    counts = results.get_counts()
Just to simplify a bit

2021-01-06 13:12 UTC, rmlarose commented on mitiq/mitiq_qiskit/tests/test_qiskit_utils.py
> +    current_exp_value = 1.0
```suggestion
    noiseless_exp_value = 1.0
```

2021-01-06 13:14 UTC, rmlarose commented on mitiq/mitiq_qiskit/tests/test_qiskit_utils.py
> +shots = 1000
Could you make these all caps? (e.g., `SHOTS` instead of `shots`) We have this convention for globals.

2021-01-06 13:17 UTC, rmlarose requested changes
Thanks @pchung39! and sorry for the late review on this. Looking very good, just a few minor comments on names, see inline comments. I think its good to be explicit with function names, and we can drop the `qs` prefix since these all live in `mitiq_qiskit` now. The other naming suggestions are just very small nits.

2021-02-09 22:02 UTC, rmlarose commented
Friendly ping on this @pchung39

2021-03-04 18:19 UTC, rmlarose commented
Another ping @pchung39. After #574 we also want to add noisy density matrix simulation without sampling.

2021-03-05 18:05 UTC, Aaron-Robertson commented
Hey @pchung39, thanks for the great work! I will pick it up from here and bring it over the finish line, unless you have an objection. Let me know, otherwise I'll make sure to include your contribution in the changelog!

2021-03-07 19:31 UTC, pchung39 commented
Hey @rmlarose so sorry I lost track of this task! @Aaron-Robertson feel free to take over and take this task across the finish line 👍

2021-03-07 23:26 UTC, rmlarose commented
> Hey @rmlarose so sorry I lost track of this task! @Aaron-Robertson feel free to take over and take this task across the finish line

No worries @pchung39 thanks for tackling the bulk of this!!

2021-03-10 16:26 UTC, rmlarose commented
Superseded by #584.

2021-03-10 16:26 UTC, closed without merging