ZNE-PEC uniformity
unitaryfund/mitiq pull request #656
Opened 2021-05-03 13:07 UTC by andre-a-alves

Description
-----------
Closes #638 
My contribution to the documentation was only about two sentences, because PEC seems to only be lightly mentioned. Also, my understanding of PEC is pretty low, so someone who understands it a little better may want to review the docstrings to make sure what I wrote was accurate; it was the best I could do.

Checklist
-----------

Check off the following once complete (or if not applicable) after opening the PR. The PR will be reviewed once this checklist is complete and all tests are passing.

- [X] I added unit tests for new code.
- [X] I used [type hints](https://www.python.org/dev/peps/pep-0484/) in function signatures.
- [X] I used [Google-style](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) docstrings for functions.
- [X] I [updated the documentation](../blob/master/docs/CONTRIBUTING_DOCS.md) where relevant.

If some items remain, you can mark this a [draft pull request](https://github.blog/2019-02-14-introducing-draft-pull-requests/).

Tips
----

- If the validation check fails:

    1. Run `make check-style` (from the root directory
  of the repository) and fix any [flake8](http://flake8.pycqa.org) errors.

    2. Run `make format` to format your code with the [black](https://black.readthedocs.io/en/stable/index.html)
  autoformatter.

  For more information, check the [style guidelines](https://mitiq.readthedocs.io/en/stable/contributing.html#style-guidelines) for Mitiq.
  
- Write "Fixes #XYZ" in the description if this PR fixes Issue #XYZ.

2021-05-10 14:54 UTC, andreamari requested changes
Thanks @andre-a-alves !  
I think this is a great PR. I only left one comment about import errors/warnings

2021-05-11 09:18 UTC, andreamari commented on mitiq/__init__.py
> -from mitiq.zne import execute_with_zne, mitigate_executor, zne_decorator
Thanks @andre-a-alves! It's not urgent, you can take all the time you need.

2021-05-12 14:14 UTC, andre-a-alves commented on mitiq/__init__.py
> -from mitiq.zne import execute_with_zne, mitigate_executor, zne_decorator
With PendingDeprecationWarning not being displayed by default, I think raising an ImportError in the future was going to be necessary, anyway, so I just went ahead and raised it now. This solution also sets a foundation from which any future import statement changes can easily be captured in the same way, including tests for raising the errors.

2021-05-12 14:15 UTC, andre-a-alves commented
Regarding the failed doctest... I ran the test on my computer and got no errors. Then I pushed, and these errors surfaced. At that point, they surfaced on my computer, too. About 20 minutes later, with nothing having changed, they are now passing on my computer. Is that common? And is there a way to initialize the test again for this PR?

2021-05-12 14:54 UTC, andreamari commented
> Regarding the failed doctest... I ran the test on my computer and got no errors. Then I pushed, and these errors surfaced. At that point, they surfaced on my computer, too. About 20 minutes later, with nothing having changed, they are now passing on my computer. Is that common? And is there a way to initialize the test again for this PR?

I re-executed the tests again and got the same error. The failing test is unrelated to this PR and will be probably fixed by #671. So I think the best strategy is merging this PR after #671.

P.s. thanks for the new import errors and tests.

2021-05-12 17:41 UTC, rmlarose commented
> Regarding the failed doctest... I ran the test on my computer and got no errors. Then I pushed, and these errors surfaced. At that point, they surfaced on my computer, too. About 20 minutes later, with nothing having changed, they are now passing on my computer. Is that common? And is there a way to initialize the test again for this PR?

Merge master to fix this now!

2021-05-19 10:11 UTC, andreamari commented
@andre-a-alves, you probably need to merge master into this branch (especially after the recent merging of #676).
Hopefully this will fix the failing doc test.

If you are participating in [unitaryHACK](https://unitaryfund.github.io/unitaryhack/), you can label this PR by writing  `[unitaryHACK]` in the title.

2021-05-20 06:14 UTC, andre-a-alves commented
Ironically, while it's passing here, I am now getting a doctest error on my machine (with a new environment that was installed from scratch, and on both this branch and on main).

2021-05-20 12:56 UTC, andreamari commented
> Ironically, while it's passing here, I am now getting a doctest error on my machine (with a new environment that was installed from scratch, and on both this branch and on main).

Did you try to re-run `pip install -r dev_requirements` after merging? If you still get the problem, feel free to open a new issue with more info about the local error. Meanwhile, since CI tests are passing, we can merge this PR.

Thanks again and congrats for the first unitaryHACK PR related to the Mitiq project!

2021-05-21 08:14 UTC, andreamari approved these changes

2021-05-21 08:15 UTC, merged

2021-07-02 01:16 UTC, crazy4pi314 commented
@all-contributors please add @andre-a-alves for doc, test