New logo for readme
unitaryfund/mitiq pull request #697
Opened 2021-05-27 17:53 UTC by crazy4pi314

Description
-----------
Adding new logo by @francespoblete to the readme! 
Co-authored-by:  Frances Joy Poblete<FrancesJoy.Poblete@haw-hamburg.de>
Closes #394 

Checklist
-----------

- [x] I added unit tests for new code.
- [x] I used [type hints](https://www.python.org/dev/peps/pep-0484/) in function signatures.
- [x] I used [Google-style](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) docstrings for functions.
- [x] I [updated the documentation](../blob/master/docs/CONTRIBUTING_DOCS.md) where relevant.

2021-05-27 21:07 UTC, crazy4pi314 commented
@rmlarose @andreamari is the doc building broke on master rn? I just merged that in here and its failing tests.

2021-05-28 10:12 UTC, andreamari commented
> @rmlarose @andreamari is the doc building broke on master rn? I just merged that in here and its failing tests.
I think sphinx doesn't like having second-level sections (`## Installation`) without having a top-level title  (`# Mitiq`)

2021-05-28 10:19 UTC, nathanshammah commented
I think it's also better to keep the markdown title as it is, and just add the logo.

2021-05-28 15:17 UTC, nathanshammah commented
It is still failing. This issue can be related: 
https://github.com/executablebooks/MyST-NB/issues/230

2021-05-28 15:20 UTC, nathanshammah commented
Actually maybe it's just a sphinx thing, e..g, https://stackoverflow.com/questions/52138336/sphinx-reference-to-an-image-from-different-locations

2021-06-05 19:04 UTC, rmlarose commented on docs/source/conf.py
> +    "html_image"
I don't think we need this anymore since it was changed to markdown image format?

2021-06-05 19:05 UTC, rmlarose commented on docs/source/conf.py
> +    "html_image"
oh, also it's duplicated from above

2021-06-05 19:05 UTC, rmlarose commented on docs/source/conf.py
> +    "html_image"
```suggestion
```

2021-06-05 19:18 UTC, rmlarose requested changes
We now have docs/assets and docs/source/img for images. Better to consolidate in my opinion.

2021-06-06 02:00 UTC, rmlarose commented
> We now have docs/assets and docs/source/img for images. Better to consolidate in my opinion.

I'll merge now and do a follow-up PR for this.

test / test is failing because coverage can't be uploaded because who the hell knows why.

2021-06-06 02:00 UTC, rmlarose approved these changes

2021-06-06 02:00 UTC, merged