Update simple_landscape.myst
unitaryfund/mitiq pull request #771
Opened 2021-06-29 19:49 UTC by DSamuel1

Description
-----------
Added noiseless curve to the simple landscape tutorial in the docs. (fixed errors in #754 ).

Checklist
-----------

Check off the following once complete (or if not applicable) after opening the PR. The PR will be reviewed once this checklist is complete and all tests are passing.

- [ ] I added unit tests for new code.
- [ ] I used [type hints](https://www.python.org/dev/peps/pep-0484/) in function signatures.
- [ ] I used [Google-style](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) docstrings for functions.
- [ ] I [updated the documentation](../blob/master/docs/CONTRIBUTING_DOCS.md) where relevant.

If some items remain, you can mark this a [draft pull request](https://github.blog/2019-02-14-introducing-draft-pull-requests/).

Tips
----

- If the validation check fails:

    1. Run `make check-types` (from the root directory of the repository) and fix any [mypy](https://mypy.readthedocs.io/en/stable/) errors.

    2. Run `make check-style` and fix any [flake8](http://flake8.pycqa.org) errors.

    3. Run `make format` to format your code with the [black](https://black.readthedocs.io/en/stable/index.html) autoformatter.

  For more information, check the [Mitiq style guidelines](https://mitiq.readthedocs.io/en/stable/contributing.html#style-guidelines).
  
- Write "Fixes #XYZ" in the description if this PR fixes Issue #XYZ.

2021-06-30 10:16 UTC, andreamari commented
Thanks @DSamuel1!
I have one final comment. The body of the noisy and noiseless executors are very similar. Can we simplify the body of `executor_with_noise`  as follows:
```
    noisy_circuit = circ.with_noise(depolarize(p))
    return noiseless_executor(noisy_circuit)
```
I think it should work.

2021-06-30 21:48 UTC, rmlarose commented on docs/source/examples/simple_landscape.myst
> +To interface with Mitiq, we now define a noiseless executor function, and a executor with noise function which compute the expctation value of a simple Hamiltonian $H=Z \otimes Z$, i.e., Pauli-$Z$ on
```suggestion
To use error mitigation methods in Mitiq, we define an executor function which computes the expectation value of a simple Hamiltonian $H=Z \otimes Z$, i.e., Pauli-$Z$ on each qubit. To compare to the noiseless result, we define both a noiseless and a noisy executor below.
```

2021-06-30 21:50 UTC, rmlarose commented on docs/source/examples/simple_landscape.myst
> +We now compute the energy lanscape $\langle H \rangle(\gamma) =\langle Z \otimes Z \rangle(\gamma)$ with no error in the following code block
```suggestion
We now compute the energy landscape $\langle H \rangle(\gamma) =\langle Z \otimes Z \rangle(\gamma)$ on the noiseless simulator.
```

2021-06-30 21:50 UTC, rmlarose commented on docs/source/examples/simple_landscape.myst
> +The following code plots the values for visualization
```suggestion
The following code plots the values for visualization.
```

2021-06-30 21:51 UTC, rmlarose commented on docs/source/examples/simple_landscape.myst
> +plt.title(rf"Energy landscape", fontsize=16)
```suggestion
plt.title("Energy landscape", fontsize=16)
```

2021-06-30 21:57 UTC, rmlarose requested changes
Thanks @DSamuel1, looking good modulo typos and wording suggestions. Please see above comments. 

Additionally, I know the following lines weren't changed in this PR but wanted to check:

https://github.com/unitaryfund/mitiq/pull/771/files#diff-695244e8c071fdea1d3c9c0c20662e37f1d5fefc1a1de3bf1c3120244732d78eR184-R194

Is the minimum energy still -1? (The landscape was changed in #742 but I didn't notice this line until now.)

Optional: You can remove the acknowledgements section. Peter contributed this before he joined the team, but since he's a team member we don't need to explicitly acknowledge him anymore.

2021-07-01 17:44 UTC, DSamuel1 commented
I've added the changes suggested by @rmlarose . As for the minimum energy, I think it should still be -1 based on the last cell?

![landscape_cell](https://user-images.githubusercontent.com/40476737/124167616-37aacf00-da72-11eb-9301-9a480e9b24bc.PNG)

2021-07-01 23:07 UTC, rmlarose commented
> I've added the changes suggested by @rmlarose . As for the minimum energy, I think it should still be -1 based on the last cell?
> 
> ![landscape_cell](https://user-images.githubusercontent.com/40476737/124167616-37aacf00-da72-11eb-9301-9a480e9b24bc.PNG)

Yup! Thanks!

2021-07-01 23:23 UTC, rmlarose approved these changes
LGTM! Thanks a lot @DSamuel1 for improving this example!

2021-07-01 23:28 UTC, merged

2021-07-02 00:52 UTC, crazy4pi314 commented
@all-contributors please add @DSamuel1 for example